name: Cluster Nuke

on:
  workflow_dispatch:         # ✅ Allow manual run from GitHub UI
  schedule:
    - cron: '10 12 * * *'     # ✅ Runs daily at 5:40 PM IST (12:10 PM UTC)

jobs:
  nuke:
    name: Nuke test namespace
    runs-on: self-hosted     # ✅ Uses your local runner (Minikube access)

    steps:
    - name: Nuke all resources in test namespace
      shell: powershell
      run: |
        Write-Host "🔥 Nuking test namespace at $(Get-Date)"
        kubectl delete all --all -n test
        kubectl delete ingress --all -n test --ignore-not-found
        kubectl delete configmap --all -n test --ignore-not-found
        kubectl delete secret --all -n test --ignore-not-found
        Write-Host "✅ Nuke complete"
